- name: app setup
  ansible.builtin.role:
    name: common
    tasks_from: app-setup.yaml

- name: install maven
  ansible.builtin.package:
    name: maven
    state: present

- name: run maven commands
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: copy jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app

- name: Install mysql
  ansible.builtin.package:
    name: mysql
    state: present

- name: Install Python 3 and MySQL connector dependencies
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
    state: present

- name: install PyMySQL for Python 3
  ansible.builtin.pip:
    name: PyMySQL
    executable: pip3

- name: run sql commands
  community.mysql.mysql_db:
    login_user: "{{ MYSQL_USER }}"
    login_password: "{{ MYSQL_PASSWORD }}"
    name: all
    state: import
    login_host: "{{ MYSQL_HOST }}"
    target: "{{ item }}"
  loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql

- name: app setup
  ansible.builtin.role:
    name: common
    tasks_from: system-setup.yaml
